# Generated by Django 4.1 on 2022-08-09 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_star_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='star',
            name='color',
            field=models.CharField(choices=[('1', 'Blue'), ('2', 'Red'), ('3', 'Brown'), ('4', 'White')], default='4', max_length=1),
        ),
    ]
