# Generated by Django 4.1 on 2022-08-10 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_star_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='star',
            name='color',
            field=models.IntegerField(choices=[(1, 'Blue'), (2, 'Red'), (3, 'Brown'), (4, 'White')], default=4),
        ),
    ]
