# Generated by Django 4.1 on 2022-08-10 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_star_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='star',
            name='size',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='star',
            name='color',
            field=models.IntegerField(),
        ),
    ]
