# Generated by Django 4.1 on 2022-08-10 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_star_size_alter_star_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='star',
            name='color',
            field=models.CharField(max_length=5),
        ),
    ]
