# Generated by Django 4.1 on 2022-08-10 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_species'),
    ]

    operations = [
        migrations.AddField(
            model_name='star',
            name='species',
            field=models.ManyToManyField(to='main_app.species'),
        ),
    ]
